services:
  - type: web
    name: mcp-demo-server
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm ci --only=production
    startCommand: npm start
    healthCheckPath: /
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    rootDir: ./

  - type: web
    name: mcp-oauth-server
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm ci --only=production
    startCommand: npm run start:oauth
    healthCheckPath: /
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: BASE_URL
        sync: false
    autoDeploy: false
    rootDir: ./