services:
  - type: web
    name: mcp-demo-server
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true

  - type: web
    name: mcp-oauth-server
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run start:oauth
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: BASE_URL
        sync: false
    autoDeploy: false